### ISSUE TITLE
IntelliJ NPE issue

### ISSUE THREAD

**Issue by zapov** [ngs-doo/dsl-compiler-client#86]
null
java.lang.NullPointerException
	at com.dslplatform.ideaplugin.DslSyntaxHighlighterFactory$MapKey.hashCode(DslSyntaxHighlighterFactory.java:23)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.dslplatform.ideaplugin.DslSyntaxHighlighterFactory.getSyntaxHighlighter(DslSyntaxHighlighterFactory.java:38)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:39)
	at com.intellij.openapi.fileTypes.LanguageFileTypeHighlighterProvider.create(LanguageFileTypeHighlighterProvider.java:31)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.util.KeyedExtensionFactory.getByKey(KeyedExtensionFactory.java:93)
	at com.intellij.openapi.util.KeyedExtensionFactory.access$000(KeyedExtensionFactory.java:34)
	at com.intellij.openapi.util.KeyedExtensionFactory$1.invoke(KeyedExtensionFactory.java:57)
	at com.sun.proxy.$Proxy89.create(Unknown Source)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:54)
	at com.intellij.openapi.fileTypes.FileTypeEditorHighlighterProviders$1.getEditorHighlighter(FileTypeEditorHighlighterProviders.java:51)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:49)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:59)
	at com.intellij.diff.util.DiffUtil.createEditorHighlighter(DiffUtil.java:173)

**Comment by zapov** [comment]
Fixed
